export const housesList = [
  // Paris
  {
    id: "p1",
    title: "Elegant Apartment Near Eiffel Tower",
    description:
      "Charming 1-bedroom apartment with a view of the Eiffel Tower. Perfect for romantic getaways.",
    price: 160,
    location: {
      city: "Paris",
      country: "France",
      address: "15 Rue de Monttessuy, Paris",
      lat: 48.8584,
      lng: 2.2945,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(1).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICgxKS53ZWJwIiwiaWF0IjoxNzQ5MDY3MDcxLCJleHAiOjE3ODA2MDMwNzF9.FWOdUc6CsLlcNK0nclqG8X5vOmuExdAwuFMOfX_3O1Y",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(1).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICgxKS53ZWJwIiwiaWF0IjoxNzQ5MDY3MDcxLCJleHAiOjE3ODA2MDMwNzF9.FWOdUc6CsLlcNK0nclqG8X5vOmuExdAwuFMOfX_3O1Y",
    ],
    rating: 4.9,
    reviews: 132,
    amenities: ["Wi-Fi", "Elevator", "Heating", "Kitchen", "Balcony"],
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    host: {
      name: "Camille Dubois",
      avatar: "https://i.pravatar.cc/150?img=31",
    },
    isSuperhost: true,
  },
  {
    id: "p2",
    title: "Stylish Flat in Le Marais",
    description:
      "Stay in the heart of Paris at this artsy flat located in the trendy Le Marais district.",
    price: 120,
    location: {
      city: "Paris",
      country: "France",
      address: "22 Rue Vieille du Temple, Paris",
      lat: 48.859,
      lng: 2.3612,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(2).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICgyKS53ZWJwIiwiaWF0IjoxNzQ5MDY3MDg3LCJleHAiOjE3ODA2MDMwODd9.7rOjktyJ5q8SA8RIjea5nwkMj8RxJ6gpPWOHtFTGBM4",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(2).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICgyKS53ZWJwIiwiaWF0IjoxNzQ5MDY3MDg3LCJleHAiOjE3ODA2MDMwODd9.7rOjktyJ5q8SA8RIjea5nwkMj8RxJ6gpPWOHtFTGBM4",
    ],
    rating: 4.7,
    reviews: 89,
    amenities: ["Wi-Fi", "Coffee Maker", "Washer", "Workspace"],
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    host: {
      name: "Louis Martin",
      avatar: "https://i.pravatar.cc/150?img=15",
    },
    isSuperhost: false,
  },
  {
    id: "p3",
    title: "Loft With Rooftop Views",
    description:
      "Bright and airy loft with rooftop terrace and skyline views. A hidden gem in central Paris.",
    price: 200,
    location: {
      city: "Paris",
      country: "France",
      address: "9 Rue Oberkampf, Paris",
      lat: 48.8635,
      lng: 2.3731,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(3).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICgzKS53ZWJwIiwiaWF0IjoxNzQ5MDY3MTE4LCJleHAiOjE3ODA2MDMxMTh9.9nH4ulv6T3B0M0YX20IUR_Wl-cdkXf2Dgtua4mEH4ms",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(3).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICgzKS53ZWJwIiwiaWF0IjoxNzQ5MDY3MTE4LCJleHAiOjE3ODA2MDMxMTh9.9nH4ulv6T3B0M0YX20IUR_Wl-cdkXf2Dgtua4mEH4ms",
    ],
    rating: 5.0,
    reviews: 74,
    amenities: ["Wi-Fi", "Terrace", "Washer", "TV", "Air Conditioning"],
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    host: {
      name: "Élise Bernard",
      avatar: "https://i.pravatar.cc/150?img=22",
    },
    isSuperhost: true,
  },
  {
    id: "p4",
    title: "Romantic Studio in Montmartre",
    description:
      "A cozy, bohemian studio tucked beneath Sacré-Cœur. Ideal for solo travelers and couples.",
    price: 85,
    location: {
      city: "Paris",
      country: "France",
      address: "5 Rue Lepic, Paris",
      lat: 48.8842,
      lng: 2.3387,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(4).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICg0KS53ZWJwIiwiaWF0IjoxNzQ5MDY3MTI0LCJleHAiOjE3ODA2MDMxMjR9.ihdCSR_1LHnnBEV1UDGZbPXWk4G7W9T2Jc7dXRZIwn0",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(4).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICg0KS53ZWJwIiwiaWF0IjoxNzQ5MDY3MTI0LCJleHAiOjE3ODA2MDMxMjR9.ihdCSR_1LHnnBEV1UDGZbPXWk4G7W9T2Jc7dXRZIwn0",
    ],
    rating: 4.6,
    reviews: 56,
    amenities: ["Wi-Fi", "Kitchenette", "Heating", "Mini Fridge"],
    guests: 2,
    bedrooms: 0,
    beds: 1,
    baths: 1,
    host: {
      name: "Julien Lefèvre",
      avatar: "https://i.pravatar.cc/150?img=5",
    },
    isSuperhost: false,
  },
  {
    id: "p5",
    title: "Luxury Duplex with Seine View",
    description:
      "Spacious duplex with river views, floor-to-ceiling windows, and high-end furnishings.",
    price: 280,
    location: {
      city: "Paris",
      country: "France",
      address: "3 Quai des Grands Augustins, Paris",
      lat: 48.8543,
      lng: 2.3449,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(5).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICg1KS53ZWJwIiwiaWF0IjoxNzQ5MDY3MTMxLCJleHAiOjE3ODA2MDMxMzF9.UUA6ct4qKI8dheGecOEfpwk2q8oXuaoog9G5KA2X3uk",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(5).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICg1KS53ZWJwIiwiaWF0IjoxNzQ5MDY3MTMxLCJleHAiOjE3ODA2MDMxMzF9.UUA6ct4qKI8dheGecOEfpwk2q8oXuaoog9G5KA2X3uk",
    ],
    rating: 4.9,
    reviews: 210,
    amenities: ["Wi-Fi", "Elevator", "Dishwasher", "Washer", "Terrace"],
    guests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 2,
    host: {
      name: "Sophie Laurent",
      avatar: "https://i.pravatar.cc/150?img=18",
    },
    isSuperhost: true,
  },
  {
    id: "p6",
    title: "Minimalist Studio near Notre-Dame",
    description:
      "Centrally located studio, 5 minutes from Notre-Dame, perfect for tourists and students.",
    price: 100,
    location: {
      city: "Paris",
      country: "France",
      address: "10 Rue du Cloître-Notre-Dame, Paris",
      lat: 48.853,
      lng: 2.3499,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(6).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICg2KS53ZWJwIiwiaWF0IjoxNzQ5MDY3MTM5LCJleHAiOjE3ODA2MDMxMzl9.5qgCiVTuhcThn3ranehHG6Lc7SDDWDRRAeFocDofz-c",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(6).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICg2KS53ZWJwIiwiaWF0IjoxNzQ5MDY3MTM5LCJleHAiOjE3ODA2MDMxMzl9.5qgCiVTuhcThn3ranehHG6Lc7SDDWDRRAeFocDofz-c",
    ],
    rating: 4.5,
    reviews: 48,
    amenities: ["Wi-Fi", "Microwave", "Heating", "Workspace"],
    guests: 2,
    bedrooms: 0,
    beds: 1,
    baths: 1,
    host: {
      name: "Théo Renault",
      avatar: "https://i.pravatar.cc/150?img=13",
    },
    isSuperhost: false,
  },
  {
    id: "p7",
    title: "Chic Apartment near Champs-Élysées",
    description:
      "Bright 2-bedroom apartment just steps from luxury boutiques and restaurants on Champs-Élysées.",
    price: 210,
    location: {
      city: "Paris",
      country: "France",
      address: "40 Avenue des Champs-Élysées, Paris",
      lat: 48.8698,
      lng: 2.3075,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(7).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICg3KS53ZWJwIiwiaWF0IjoxNzQ5MDY3MTQ2LCJleHAiOjE3ODA2MDMxNDZ9.aUaYJACTJ8CKJQeCMr6FU2Ll9G7rLG8b4T8npbUDpYI",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(7).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICg3KS53ZWJwIiwiaWF0IjoxNzQ5MDY3MTQ2LCJleHAiOjE3ODA2MDMxNDZ9.aUaYJACTJ8CKJQeCMr6FU2Ll9G7rLG8b4T8npbUDpYI",
    ],
    rating: 4.8,
    reviews: 95,
    amenities: ["Wi-Fi", "TV", "Coffee Machine", "Bathtub", "Elevator"],
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    host: {
      name: "Claire Petit",
      avatar: "https://i.pravatar.cc/150?img=25",
    },
    isSuperhost: true,
  },
  {
    id: "p8",
    title: "Quiet Flat Near Luxembourg Gardens",
    description:
      "Relaxing and quiet flat ideal for families or remote workers. Steps from gardens and cafés.",
    price: 130,
    location: {
      city: "Paris",
      country: "France",
      address: "67 Rue d'Assas, Paris",
      lat: 48.8456,
      lng: 2.3308,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(8).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICg4KS53ZWJwIiwiaWF0IjoxNzQ5MDY3MTUzLCJleHAiOjE3ODA2MDMxNTN9.dTccW_w4ohJT7kPs9dd5N2OzHEk6JTAwxYtFgYnpttQ",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/paris-houses%20(8).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvcGFyaXMtaG91c2VzICg4KS53ZWJwIiwiaWF0IjoxNzQ5MDY3MTUzLCJleHAiOjE3ODA2MDMxNTN9.dTccW_w4ohJT7kPs9dd5N2OzHEk6JTAwxYtFgYnpttQ",
    ],
    rating: 4.7,
    reviews: 60,
    amenities: ["Wi-Fi", "Washer", "Kitchen", "Crib", "Heating"],
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    host: {
      name: "Antoine Girard",
      avatar: "https://i.pravatar.cc/150?img=19",
    },
    isSuperhost: false,
  },
  // London
  {
    id: "hs-01",
    title: "Cozy Loft in Manhattan",
    description:
      "Stylish 2-bedroom loft located in the heart of Manhattan, just steps from Times Square. High ceilings and skyline views.",
    price: 250,
    location: {
      city: "London",
      country: "USA",
      address: "123 Broadway, New York, NY",
      lat: 40.7128,
      lng: -74.006,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/London%20Houses%20(1).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvTG9uZG9uIEhvdXNlcyAoMSkud2VicCIsImlhdCI6MTc0OTA3NzExOCwiZXhwIjoxNzgwNjEzMTE4fQ.oXqWoHv7oVq4YaoTywZAVaZH3JrH-SLXEX07n5jDgL8",
    images: [
      "https://example.com/images/nyc-loft-1.jpg",
      "https://example.com/images/nyc-loft-2.jpg",
      "https://example.com/images/nyc-loft-3.jpg",
    ],
    rating: 4.7,
    reviews: 98,
    amenities: ["Wi-Fi", "Air Conditioning", "Washer", "Kitchen", "Elevator"],
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    host: {
      name: "Michael Thompson",
      avatar: "https://i.pravatar.cc/150?img=32",
    },
    isSuperhost: false,
  },
  {
    id: "hs-02",
    title: "Traditional Ryokan in Kyoto",
    description:
      "Authentic Japanese ryokan with tatami rooms and futons. Enjoy a serene garden and onsen experience in central Kyoto.",
    price: 180,
    location: {
      city: "London",
      country: "Japan",
      address: "45 Gionmachi Minamigawa, Higashiyama-ku, Kyoto",
      lat: 35.0116,
      lng: 135.7681,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/London%20Houses%20(2).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvTG9uZG9uIEhvdXNlcyAoMikud2VicCIsImlhdCI6MTc0OTA3NzEyNCwiZXhwIjoxNzgwNjEzMTI0fQ.vJKOXXGBLQIRbnBXLNzqsMc7L-mMAj4oPu1qz4AwqcA",
    images: [
      "https://example.com/images/kyoto-ryokan-1.jpg",
      "https://example.com/images/kyoto-ryokan-2.jpg",
      "https://example.com/images/kyoto-ryokan-3.jpg",
    ],
    rating: 4.9,
    reviews: 210,
    amenities: [
      "Hot Water Onsen",
      "Housekeeping",
      "Tea Set",
      "Japanese Breakfast",
      "Garden View",
    ],
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    host: {
      name: "Sakura Nakamura",
      avatar: "https://i.pravatar.cc/150?img=33",
    },
    isSuperhost: true,
  },
  {
    id: "hs-03",
    title: "Overwater Bungalow in the Maldives",
    description:
      "Luxurious overwater bungalow with private deck and direct ocean access. Perfect for honeymooners seeking tranquility.",
    price: 450,
    location: {
      city: "London",
      country: "Maldives",
      address: "Island Noonu Atoll, Maldives",
      lat: 3.2028,
      lng: 73.2207,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/London%20Houses%20(3).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvTG9uZG9uIEhvdXNlcyAoMykud2VicCIsImlhdCI6MTc0OTA3NzEzMSwiZXhwIjoxNzgwNjEzMTMxfQ.uafQa2TosS7qxewBMnfV2QfjMgCKYrXcderaq9WLyp0",
    images: [
      "https://example.com/images/maldives-bungalow-1.jpg",
      "https://example.com/images/maldives-bungalow-2.jpg",
      "https://example.com/images/maldives-bungalow-3.jpg",
    ],
    rating: 5.0,
    reviews: 64,
    amenities: [
      "Private Deck",
      "Snorkeling Gear",
      "Air Conditioning",
      "Mini Bar",
      "Ocean View",
    ],
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    host: {
      name: "Aisha Hassan",
      avatar: "https://i.pravatar.cc/150?img=34",
    },
    isSuperhost: true,
  },
  {
    id: "hs-04",
    title: "Rustic Cabin in the Swiss Alps",
    description:
      "Charming wooden cabin nestled in the Swiss Alps near Zermatt. Fireplace, mountain views, and ski-in/ski-out access.",
    price: 320,
    location: {
      city: "London",
      country: "Switzerland",
      address: "Munggästrasse 7, 3920 Zermatt",
      lat: 46.0207,
      lng: 7.7491,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/London%20Houses%20(4).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvTG9uZG9uIEhvdXNlcyAoNCkud2VicCIsImlhdCI6MTc0OTA3NzEzNywiZXhwIjoxNzgwNjEzMTM3fQ.GO6VnRpipPlAxkMkRx35nZkXTvcSYGRj7mUQd3zRgJo",
    images: [
      "https://example.com/images/zermatt-cabin-1.jpg",
      "https://example.com/images/zermatt-cabin-2.jpg",
      "https://example.com/images/zermatt-cabin-3.jpg",
    ],
    rating: 4.8,
    reviews: 76,
    amenities: [
      "Fireplace",
      "Kitchen",
      "Parking",
      "Mountain View",
      "Ski Equipment",
    ],
    guests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 1,
    host: {
      name: "Lukas Müller",
      avatar: "https://i.pravatar.cc/150?img=35",
    },
    isSuperhost: false,
  },
  {
    id: "hs-05",
    title: "Modern Penthouse in Dubai Marina",
    description:
      "Spacious penthouse with 360° views of Dubai Skyline and the Arabian Gulf. Rooftop pool, gym access, and private parking.",
    price: 400,
    location: {
      city: "London",
      country: "UAE",
      address: "Marina Promenade, Dubai Marina, Dubai",
      lat: 25.0859,
      lng: 55.1424,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/London%20Houses%20(5).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvTG9uZG9uIEhvdXNlcyAoNSkud2VicCIsImlhdCI6MTc0OTA3NzE0OSwiZXhwIjoxNzgwNjEzMTQ5fQ.d_-hHJAus61FOqXLdR_Z3gcJXCFI8Jad-2I6Q5WChvE",
    images: [
      "https://example.com/images/dubai-penthouse-1.jpg",
      "https://example.com/images/dubai-penthouse-2.jpg",
      "https://example.com/images/dubai-penthouse-3.jpg",
    ],
    rating: 4.6,
    reviews: 54,
    amenities: [
      "Rooftop Pool",
      "Gym Access",
      "Wi-Fi",
      "Air Conditioning",
      "Parking",
    ],
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    host: {
      name: "Fatima Al Rashid",
      avatar: "https://i.pravatar.cc/150?img=36",
    },
    isSuperhost: true,
  },
  {
    id: "hs-06",
    title: "Charming Bungalow in Ubud",
    description:
      "Beautiful Balinese bungalow surrounded by rice terraces and tropical gardens. Outdoor shower and yoga deck included.",
    price: 120,
    location: {
      city: "London",
      country: "Indonesia",
      address: "Jl. Raya Ubud, Ubud, Gianyar, Bali",
      lat: -8.5069,
      lng: 115.2624,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/London%20Houses%20(6).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvTG9uZG9uIEhvdXNlcyAoNikud2VicCIsImlhdCI6MTc0OTA3NzE1NiwiZXhwIjoxNzgwNjEzMTU2fQ.CcrHqujlass6XH5A2ZGBqywrMnlGI2-pDgisNxul0_k",
    images: [
      "https://example.com/images/ubud-bungalow-1.jpg",
      "https://example.com/images/ubud-bungalow-2.jpg",
      "https://example.com/images/ubud-bungalow-3.jpg",
    ],
    rating: 4.9,
    reviews: 145,
    amenities: [
      "Outdoor Shower",
      "Yoga Deck",
      "Kitchenette",
      "Garden View",
      "Free Breakfast",
    ],
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    host: {
      name: "Putri Saraswati",
      avatar: "https://i.pravatar.cc/150?img=37",
    },
    isSuperhost: false,
  },
  {
    id: "hs-07",
    title: "Historic Castle in Stirling",
    description:
      "Stay in a fully restored medieval castle overlooking Stirling Castle. Four bedrooms, grand dining hall, and sweeping countryside views.",
    price: 600,
    location: {
      city: "London",
      country: "United Kingdom",
      address: "Castle Road, Stirling FK8 1EJ",
      lat: 56.1165,
      lng: -3.9369,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/London%20Houses%20(7).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvTG9uZG9uIEhvdXNlcyAoNykud2VicCIsImlhdCI6MTc0OTA3NzE2MywiZXhwIjoxNzgwNjEzMTYzfQ.yj2jhbXEglfgNNhsuDk_0kexqLDQmIMf2-UpHujjVA4",
    images: [
      "https://example.com/images/stirling-castle-1.jpg",
      "https://example.com/images/stirling-castle-2.jpg",
      "https://example.com/images/stirling-castle-3.jpg",
    ],
    rating: 5.0,
    reviews: 38,
    amenities: [
      "Fireplace",
      "Fully Equipped Kitchen",
      "Parking",
      "Historic Library",
      "Countryside View",
    ],
    guests: 8,
    bedrooms: 4,
    beds: 6,
    baths: 3,
    host: {
      name: "Alastair Campbell",
      avatar: "https://i.pravatar.cc/150?img=38",
    },
    isSuperhost: true,
  },
  // New York
  {
    id: "ny-01",
    title: "Sunny Studio in SoHo",
    description:
      "Bright and modern studio apartment located in the heart of SoHo. Perfect for couples or solo travelers, steps away from galleries and boutiques.",
    price: 200,
    location: {
      city: "New York",
      country: "USA",
      address: "50 Prince St, New York, NY 10012",
      lat: 40.7233,
      lng: -73.9967,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(1).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDEpLndlYnAiLCJpYXQiOjE3NDkwNzc3MzIsImV4cCI6MTc4MDYxMzczMn0.l_sLk_Io1HfDVkxamvtIrWNhQb30ROvaM0UiewxD7j4",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(1).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDEpLndlYnAiLCJpYXQiOjE3NDkwNzc3MzIsImV4cCI6MTc4MDYxMzczMn0.l_sLk_Io1HfDVkxamvtIrWNhQb30ROvaM0UiewxD7j4",
    ],
    rating: 4.8,
    reviews: 112,
    amenities: ["Wi-Fi", "Air Conditioning", "Heating", "Kitchen", "Washer"],
    guests: 2,
    bedrooms: 0,
    beds: 1,
    baths: 1,
    host: {
      name: "Olivia Harris",
      avatar: "https://i.pravatar.cc/150?img=39",
    },
    isSuperhost: true,
  },
  {
    id: "ny-02",
    title: "Chic One-Bedroom in Williamsburg",
    description:
      "Cozy one-bedroom apartment with Edison bulb lighting and exposed brick walls. Located in trendy Williamsburg, close to bars and cafes.",
    price: 180,
    location: {
      city: "New York",
      country: "USA",
      address: "95 Wythe Ave, Brooklyn, NY 11249",
      lat: 40.7209,
      lng: -73.957,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(2).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDIpLndlYnAiLCJpYXQiOjE3NDkwNzc3NDAsImV4cCI6MTc4MDYxMzc0MH0.a6ROACNVJvOmG5Z-zUut0riwK-99BG6TqGeeWmc5bP0",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(2).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDIpLndlYnAiLCJpYXQiOjE3NDkwNzc3NDAsImV4cCI6MTc4MDYxMzc0MH0.a6ROACNVJvOmG5Z-zUut0riwK-99BG6TqGeeWmc5bP0",
    ],
    rating: 4.5,
    reviews: 87,
    amenities: [
      "Wi-Fi",
      "Heating",
      "Kitchen",
      "Coffee Maker",
      "Free Street Parking",
    ],
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    host: {
      name: "Ethan Carter",
      avatar: "https://i.pravatar.cc/150?img=40",
    },
    isSuperhost: false,
  },
  {
    id: "ny-03",
    title: "Luxury Two-Bedroom Near Central Park",
    description:
      "Spacious two-bedroom apartment with floor-to-ceiling windows and Central Park views. Prime Upper West Side location.",
    price: 350,
    location: {
      city: "New York",
      country: "USA",
      address: "200 W 72nd St, New York, NY 10023",
      lat: 40.7781,
      lng: -73.9802,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(3).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDMpLndlYnAiLCJpYXQiOjE3NDkwNzc3NDgsImV4cCI6MTc4MDYxMzc0OH0.nYj4l4V4ORqsR08ayUQmGjpRalj41k1LbTgLS2Mvb_g",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(3).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDMpLndlYnAiLCJpYXQiOjE3NDkwNzc3NDgsImV4cCI6MTc4MDYxMzc0OH0.nYj4l4V4ORqsR08ayUQmGjpRalj41k1LbTgLS2Mvb_g",
    ],
    rating: 4.9,
    reviews: 156,
    amenities: [
      "Wi-Fi",
      "Air Conditioning",
      "Elevator",
      "Gym Access",
      "Washer/Dryer",
    ],
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    host: {
      name: "Isabella Reed",
      avatar: "https://i.pravatar.cc/150?img=41",
    },
    isSuperhost: true,
  },
  {
    id: "ny-04",
    title: "Historic Brownstone in Harlem",
    description:
      "Charming brownstone townhouse conversion with vintage decor. Close to Apollo Theater and local jazz clubs.",
    price: 220,
    location: {
      city: "New York",
      country: "USA",
      address: "145 W 124th St, New York, NY 10027",
      lat: 40.8075,
      lng: -73.945,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(4).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDQpLndlYnAiLCJpYXQiOjE3NDkwNzc3NTcsImV4cCI6MTc4MDYxMzc1N30.ADolxySRm1GtfAde-u8GZvfGuxs2La60MOKKSgKG6rA",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(4).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDQpLndlYnAiLCJpYXQiOjE3NDkwNzc3NTcsImV4cCI6MTc4MDYxMzc1N30.ADolxySRm1GtfAde-u8GZvfGuxs2La60MOKKSgKG6rA",
    ],
    rating: 4.6,
    reviews: 64,
    amenities: ["Wi-Fi", "Heating", "Kitchen", "Washer", "Street Parking"],
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    host: {
      name: "Marcus Lee",
      avatar: "https://i.pravatar.cc/150?img=42",
    },
    isSuperhost: false,
  },
  {
    id: "ny-05",
    title: "Loft with Empire State Views",
    description:
      "Open-plan loft in Midtown with direct views of the Empire State Building. Industrial-chic style, cat-friendly, in-unit laundry.",
    price: 275,
    location: {
      city: "New York",
      country: "USA",
      address: "350 5th Ave, New York, NY 10118",
      lat: 40.7484,
      lng: -73.9857,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(5).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDUpLndlYnAiLCJpYXQiOjE3NDkwNzc3NjcsImV4cCI6MTc4MDYxMzc2N30.0Ofo8ndiChgovLqo0Vn2k7Au69TX1jVpCkb55Wh0rZE",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(5).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDUpLndlYnAiLCJpYXQiOjE3NDkwNzc3NjcsImV4cCI6MTc4MDYxMzc2N30.0Ofo8ndiChgovLqo0Vn2k7Au69TX1jVpCkb55Wh0rZE",
    ],
    rating: 4.7,
    reviews: 105,
    amenities: [
      "Wi-Fi",
      "Air Conditioning",
      "Elevator",
      "Washer/Dryer",
      "Cat Friendly",
    ],
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    host: {
      name: "Sophia Martinez",
      avatar: "https://i.pravatar.cc/150?img=43",
    },
    isSuperhost: true,
  },
  {
    id: "ny-06",
    title: "Penthouse with Brooklyn Bridge View",
    description:
      "Elegant penthouse suite overlooking the Brooklyn Bridge and East River. Rooftop terrace and 24-hour concierge included.",
    price: 500,
    location: {
      city: "New York",
      country: "USA",
      address: "1 Old Fulton St, Brooklyn, NY 11201",
      lat: 40.7021,
      lng: -73.9936,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(6).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDYpLndlYnAiLCJpYXQiOjE3NDkwNzc3NzYsImV4cCI6MTc4MDYxMzc3Nn0.UFp2rFq0vRVJm7DnUjYwnZYbsbCgKbF_mOW3lp8iWQ8",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(6).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDYpLndlYnAiLCJpYXQiOjE3NDkwNzc3NzYsImV4cCI6MTc4MDYxMzc3Nn0.UFp2rFq0vRVJm7DnUjYwnZYbsbCgKbF_mOW3lp8iWQ8",
    ],
    rating: 4.9,
    reviews: 48,
    amenities: [
      "Wi-Fi",
      "Air Conditioning",
      "Elevator",
      "Rooftop Terrace",
      "24hr Concierge",
    ],
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    host: {
      name: "Liam Brooks",
      avatar: "https://i.pravatar.cc/150?img=44",
    },
    isSuperhost: true,
  },
  {
    id: "ny-07",
    title: "Bright Loft in DUMBO",
    description:
      "Artistic loft with exposed beams and large windows, located in DUMBO. Stroll to Brooklyn Bridge Park and waterfront cafés.",
    price: 240,
    location: {
      city: "New York",
      country: "USA",
      address: "97 Front St, Brooklyn, NY 11201",
      lat: 40.7033,
      lng: -73.9881,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(7).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDcpLndlYnAiLCJpYXQiOjE3NDkwNzc3ODQsImV4cCI6MTc4MDYxMzc4NH0.sdFy27lpufVtII4bxzrGvVKcLciZtgK8V5cFIj_2QrM",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(7).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDcpLndlYnAiLCJpYXQiOjE3NDkwNzc3ODQsImV4cCI6MTc4MDYxMzc4NH0.sdFy27lpufVtII4bxzrGvVKcLciZtgK8V5cFIj_2QrM",
    ],
    rating: 4.4,
    reviews: 59,
    amenities: ["Wi-Fi", "Kitchen", "Washer", "Heating", "Street Parking"],
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    host: {
      name: "Ava Wilson",
      avatar: "https://i.pravatar.cc/150?img=45",
    },
    isSuperhost: false,
  },
  {
    id: "ny-08",
    title: "Elegant Flat on Park Avenue",
    description:
      "Sophisticated one-bedroom flat on Park Avenue with marble bath and concierge service. Close to Museum Mile and Madison Avenue shopping.",
    price: 330,
    location: {
      city: "New York",
      country: "USA",
      address: "400 Park Ave, New York, NY 10022",
      lat: 40.7601,
      lng: -73.973,
    },
    thumbnail:
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(8).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDgpLndlYnAiLCJpYXQiOjE3NDkwNzc3OTEsImV4cCI6MTc4MDYxMzc5MX0.Pupp8_gcXSKoAvpMNJIP33U_rFBhaqKF3-tW9SYqSBQ",
    images: [
      "https://eebmpmdmqmndwpalqeux.supabase.co/storage/v1/object/sign/houses/newyork-houses%20(8).webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wZGNjNTdjMy0wMWRhLTQ2NTgtYmUyZS00M2ZkOWYyMzUyOTUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJob3VzZXMvbmV3eW9yay1ob3VzZXMgKDgpLndlYnAiLCJpYXQiOjE3NDkwNzc3OTEsImV4cCI6MTc4MDYxMzc5MX0.Pupp8_gcXSKoAvpMNJIP33U_rFBhaqKF3-tW9SYqSBQ",
    ],
    rating: 4.8,
    reviews: 74,
    amenities: [
      "Wi-Fi",
      "Air Conditioning",
      "Elevator",
      "Doorman",
      "Washer/Dryer",
    ],
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    host: {
      name: "Mia Thompson",
      avatar: "https://i.pravatar.cc/150?img=46",
    },
    isSuperhost: true,
  },
];
